<html>
    <head>
        <title> Writing PHP funtion with parameter</title>
    </head>
    <body>
        <?php
            function Add($a, $b)
            {
                $sum = $a + $b;
                echo "Sum = $sum";
            }

            Add(10, 20);

            echo "<br>This program is Written and Exceuted by DHAANI SANGWAN(2220100253)";
        ?>
    </body>
</html>